# Generated by Django 4.1.7 on 2023-09-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankTransferReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt", models.FileField(upload_to="receipt/")),
                ("order_id", models.CharField(max_length=20)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
