disposable_mails = [".ga", "emailage.gq", "emailage.ml", "emailage.tk", "emaildienst.de", 
                    "emailgo.de", "emailias.com", "emailigo.de", "emailinfive.com", "emaillime.com", 
                    "emailmiser.com", "emailproxsy.com", "emailresort.com", "emailsensei.com", 
                    "emailtemporar.ro", "emailtemporario.com.br", "emailthe.net", "emailtmp.com", 
                    "emailto.de", "emailwarden.com", "emailx.at.hm", "emailxfer.com", "emeil.in", 
                    "emeil.ir", "emz.net", "ero-tube.org", "evopo.com", "explodemail.com", 
                    "express.net.ua", "eyepaste.com", "fakeinbox.com", "fakeinformation.com", 
                    "fakemail.fr", "fakemailgenerator.com", "fansworldwide.de", "fantasymail.de", 
                    "fastacura.com", "fastchevy.com", "fastchrysler.com", "fastkawasaki.com", 
                    "fastmazda.com", "fastmitsubishi.com", "fastnissan.com", "fastsubaru.com", 
                    "fastsuzuki.com", "fasttoyota.com", "fastyamaha.com", "fightallspam.com", 
                    "filzmail.com", "fivemail.de", "fizmail.com", "fleckens.hu", "fr33mail.info", 
                    "frapmail.com", "friendlymail.co.uk", "fuckingduh.com", "fudgerub.com", 
                    "fux0ringduh.com", "garliclife.com", "gehensiemirnichtaufdensack.de", "get1mail.com", 
                    "get2mail.fr", "getairmail.com", "getmails.eu", "getonemail.com", "getonemail.net", 
                    "ghosttexter.de", "giantmail.de", "girlsundertheinfluence.com", "gishpuppy.com", 
                    "gowikibooks.com", "gowikicampus.com", "gowikicars.com", "gowikifilms.com", 
                    "gowikigames.com", "gowikimusic.com", "gowikinetwork.com", "gowikitravel.com", 
                    "gowikitv.com", "great-host.in", "greensloth.com", "grr.la", "gsrv.co.uk", 
                    "guerillamail.biz", "guerillamail.com", "guerrillamail.biz", "guerrillamail.com", 
                    "guerrillamail.de", "guerrillamail.info", "guerrillamail.net", "guerrillamail.org", 
                    "guerrillamailblock.com", "gustr.com", "h.mintemail.com", "h8s.org", "haltospam.com", 
                    "harakirimail.com", "hat-geld.de", "hatespam.org", "herp.in", "hidemail.de", "hidzz.com", 
                    "hmamail.com", "hopemail.biz", "hulapla.de", "ieatspam.eu", "ieatspam.info", "ihateyoualot.info", 
                    "ihazspam.ca", "iheartspam.org", "ikbenspamvrij.nl", "imails.info", "inbax.tk", "inbox.si", 
                    "inboxalias.com", "inboxclean.com", "inboxclean.org", "infocom.zp.ua", "insorg-mail.info", 
                    "instant-mail.de", "ipoo.org", "irish2me.com", "iwi.net", "jetable.com", "jetable.fr.nf", 
                    "jetable.net", "jetable.org", "jnxjn.com", "jourrapide.com", "jsrsolutions.com", "junk1e.com", 
                    "kasmail.com", "kaspop.com", "keepmymail.com", "killmail.com", "killmail.net", "kir.ch.tc", 
                    "klassmaster.com", "klzlk.com", "kook.ml", "koszmail.pl", "kurzepost.de", "lawlita.com", 
                    "letthemeatspam.com", "lhsdv.com", "lifebyfood.com", "link2mail.net", "litedrop.com", 
                    "lol.ovpn.to", "lolfreak.net", "lookugly.com", "lopl.co.cc", "lr78.com", "lroid.com", 
                    "lukop.dk", "m21.cc", "m4ilweb.info", "maboard.com", "mail-filter.com", "mail-temporaire.fr", 
                    "mail.by", "mail.mezimages.net", "mail.zp.ua", "mail114.net", "mail1a.de", "mail21.cc", 
                    "mail2rss.org", "mail333.com", "mail4trash.com", "mailbidon.com", "mailbiz.biz", 
                    "mailblocks.com", "mailbucket.org", "mailcat.biz", "mailcatch.com", "mailde.de", 
                    "mailde.info", "maildrop.cc", "maildx.com", "maileater.com", "maileimer.de", 
                    "mailexpire.com", "mailfa.tk", "mailforspam.com", "mailfreeonline.com", "mailguard.me", 
                    "mailhazard.com", "mailhazard.us", "mailhz.me", "mailimate.com", "mailin8r.com", 
                    "mailinater.com", "mailinator.com", "mailinator.net", "mailinator.org", "mailinator2.com", 
                    "mailincubator.com", "mailismagic.com", "mailita.tk", "mailjunk.cf", "mailjunk.ga", 
                    "mailjunk.gq", "mailjunk.ml", "mailjunk.tk", "mailme.ir", "mailme.lv", "mailme24.com", 
                    "mailmetrash.com", "mailms.com", "mailnesia.com", "mailnull.com", "mailorg.org", 
                    "mailpick.biz", "mailproxsy.com", "mailquack.com", "mailrock.biz", "mailsac.com", 
                    "mailscrap.com", "mailshell.com", "mailsiphon.com", "mailslite.com", "mailtemp.info", 
                    "mailtome.de", "mailtothis.com", "mailtrash.net", "mailtv.net", "mailtv.tv", "mailzilla.com", 
                    "makemetheking.com", "manybrain.com", "mbx.cc", "mega.zik.dj", "meinspamschutz.de", 
                    "meltmail.com", "messagebeamer.de", "mezimages.net", "mierdamail.com", 
                    "ministry-of-silly-walks.de", "mintemail.com", "misterpinball.de", "moburl.com", 
                    "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf", "monumentmail.com", 
                    "msa.minsmail.com", "mt2009.com", "mt2014.com", "mycard.net.ua", "mycleaninbox.net", 
                    "myemailboxy.com", "mymail-in.net", "mypacks.net", "mypartyclip.de", "myphantomemail.com", 
                    "mysamp.de", "mytempemail.com", "mytempmail.com", "mytrashmail.com", "nabuma.com", 
                    "neomailbox.com", "nepwk.com", "nervmich.net", "nervtmich.net", "netmails.com", 
                    "netmails.net", "netricity.nl", "netris.net", "netzidiot.de", "neverbox.com", 
                    "nice-4u.com", "nincsmail.com", "nincsmail.hu", "nobulk.com", "noclickemail.com", 
                    "nogmailspam.info", "nomail.pw", "nomail.xl.cx", "nomail2me.com", "nomorespamemails.com", 
                    "nonspam.eu", "nonspammer.de", "noref.in", "nospam.wins.com.br", "nospam.ze.tc", 
                    "nospam4.us", "nospamfor.us", "nospammail.net", "nospamthanks.info", "notmailinator.com", 
                    "notsharingmy.info", "nowhere.org", "nowmymail.com", "nurfuerspam.de", "nus.edu.sg", 
                    "objectmail.com", "obobbo.com", "oneoffemail.com", "onewaymail.com", "onlatedotcom.info", 
                    "online.ms", "opayq.com", "ordinaryamerican.net", "otherinbox.com", "ourklips.com", 
                    "outlawspam.com", "ovpn.to", "owlpic.com", "pancakemail.com", "paplease.com", "pcusers.otherinbox.com", 
                    "pjjkp.com", "plexolan.de", "politikerclub.de", "poofy.org", "pookmail.com", "privacy.net", 
                    "privatdemail.net", "proxymail.eu", "prtnx.com", "punkass.com", "putthisinyourspamdatabase.com", 
                    "pwrby.com", "qq.com", "quickinbox.com", "rcpt.at", "recode.me", "recursor.net", "recyclemail.dk", 
                    "redchan.it", "regbypass.comsafe-mail.net", "safersignup.de", "safetymail.info", "safetypost.de", 
                    "sandelf.de", "saynotospams.com", "schafmail.de", "schrott-email.de", "secretemail.de", 
                    "secure-mail.biz", "selfdestructingmail.com", "selfdestructingmail.org", "sendspamhere.com", 
                    "sharklasers.com", "shieldemail.com", "shiftmail.com", "shitmail.de", "shitware.nl", 
                    "shmeriously.com", "shortmail.net", "sibmail.com", "sinnlos-mail.de", "skeefmail.com", 
                    "slapsfromlastnight.com", "slaskpost.se", "slopsbox.com", "slushmail.com", "smaakt.naar.gravel", 
                    "smapfree24.com", "smapfree24.de", "smapfree24.eu", "smapfree24.info", "smapfree24.org", 
                    "smashmail.de", "smellfear.com", "snakemail.com", "sneakemail.com", "sneakmail.de", 
                    "snkmail.com", "sofimail.com", "sofort-mail.de", "sogetthis.com", "solvemail.info", 
                    "soodonims.com", "spam.la", "spam.su", "spam4.me", "spamail.de", "spamarrest.com", 
                    "spamavert.com", "spambob.com", "spambob.net", "spambob.org", "spambog.com", "spambog.de", 
                    "spambog.net", "spambog.ru", "spambooger.com", "spambox.info", "spambox.irishspringrealty.com", 
                    "spambox.me", "spambox.org", "spambox.us", "spamcannon.com", "spamcannon.net", "spamcero.com", 
                    "spamcon.org", "spamcorptastic.com", "spamcowboy.com", "spamcowboy.net", "spamcowboy.org", 
                    "spamday.com", "spamex.com", "spamfighter.cf", "spamfighter.ga", "spamfighter.gq", 
                    "spamfighter.ml", "spamfighter.tk", "spamfree.eu", "spamfree24.com", "spamfree24.de", 
                    "spamfree24.eu", "spamfree24.info", "spamfree24.net", "spamfree24.org", "spamgoes.in", 
                    "spamgourmet.com", "spamgourmet.net", "spamgourmet.org", "spamherelots.com", "spamherelots.com", 
                    "spamhereplease.com", "spamhole.com", "spamify.com", "spaminator.de", "spamkill.info", 
                    "spaml.com", "spaml.de", "spamlot.net", "spammotel.com", "spamobox.com", "spamoff.de", 
                    "spamsalad.in", "spamserver.cf", "spamserver.ml", "spamserver.tk", "spamshuttle.com", 
                    "spamspameverywhere.org", "spamspot.com", "spamthis.co.uk", "spamthisplease.com", 
                    "spamtrail.com", "spamtroll.net", "speed.1s.fr", "spoofmail.de", "stuffmail.de", 
                    "super-auswahl.de", "supergreatmail.com", "supermailer.jp", "superplatyna.com", 
                    "superrito.com", "superstachel.de", "suremail.info", "teewars.org", "teleworm.com", 
                    "teleworm.us", "temp-mail.com", "temp-mail.de", "temp-mail.org", "temp.headstrong.de", 
                    "tempail.com", "tempalias.com", "tempe-mail.com", "tempemail.biz", "tempemail.co.za", 
                    "tempemail.com", "tempemail.net", "tempinbox.co.uk", "tempinbox.com", "tempmail.co", 
                    "tempmail.de", "tempmail.eu", "tempmail.it", "tempmail.net", "tempmail.org", "tempmail.us", 
                    "tempmail2.com", "tempmaildemo.com", "tempmailer.com", "tempmailer.de", "tempomail.fr", 
                    "temporarily.de", "temporarioemail.com.br", "temporaryemail.net", "temporaryemail.us", 
                    "temporaryforwarding.com", "temporaryinbox.com", "temporarymailaddress.com", "tempthe.net", 
                    "thankyou2010.com", "thc.st", "thelimestones.com", "thisisnotmyrealemail.com", "thismail.net", 
                    "thrma.com", "throwawayemailaddress.com", "tilien.com", "tittbit.in", "tizi.com", 
                    "tmailinator.com", "toomail.biz", "topranklist.de", "tradermail.info", "trash-amil.com", 
                    "trash-mail.at", "trash-mail.com", "trash-mail.de", "trash2009.com", "trashdevil.com", 
                    "trashemail.de", "trashmail.at", "trashmail.com", "trashmail.de", "trashmail.io", 
                    "trashmail.me", "trashmail.net", "trashmail.org", "trashmail.ws", "trashmailer.com", 
                    "trashymail.com", "trashymail.net", "trialmail.de", "trillianpro.com", "tryalert.com", 
                    "turual.com", "twinmail.de", "tyldd.com", "uggsrock.com", "umail.net", "uroid.com", 
                    "us.af", "valemail.net", "venompen.com", "veryrealemail.com", "viditag.com", "viralplays.com", 
                    "vpn.st", "vsimcard.com", "vubby.com", "wasteland.rfc822.org", "webemail.me", 
                    "wegwerf-emails.de", "wegwerfadresse.de", "wegwerfemail.com", "wegwerfemail.de", 
                    "wegwerfmail.de", "wegwerfmail.info", "wegwerfmail.net", "wegwerfmail.org", "wetrainbayarea.com", 
                    "wetrainbayarea.org", "wh4f.org", "whyspam.me", "willhackforfood.biz", "willselfdestruct.com", 
                    "winemaven.info", "wronghead.com", "www.e4ward.com", "www.mailinator.com", "wwwnew.eu", 
                    "x.ip6.li", "xagloo.com", "xemaps.com", "xents.com", "xmail.com", "xmaily.com", "xoxy.net", 
                    "yep.it", "yogamaven.com", "yopmail.com", "yopmail.fr", "yopmail.net", "yourdomain.com", 
                    "ypmail.webarnak.fr.eu.org", "yuurok.com", "z1p.biz", "za.com", "zehnminutenmail.de", 
                    "zehnminutenmail.net", "zehnminutenmail.org", "zippymail.info", "zoaxe.com", "zoemail.net", "zomg.info"]