# Generated by Django 4.1.7 on 2023-08-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sevis", "0002_sevisinformationuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sevisinformationuser",
            name="order_fee",
        ),
    ]
