# Generated by Django 4.1.7 on 2023-09-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevis", "0003_remove_sevisinformationuser_order_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sevisinformationuser",
            name="street_address_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
