# Generated by Django 4.1.7 on 2023-09-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevis", "0004_alter_sevisinformationuser_street_address_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sevisinformationguest",
            name="street_address_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
