# Generated by Django 4.1.7 on 2023-09-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevis", "0005_alter_sevisinformationguest_street_address_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="sevisinformationuser",
            name="sevis_coupon",
            field=models.FileField(blank=True, null=True, upload_to="sevis_coupon/"),
        ),
    ]
