# Generated by Django 4.1.7 on 2023-09-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevis", "0006_sevisinformationuser_sevis_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="sevisinformationuser",
            name="sevis_fee",
            field=models.CharField(blank=True, default="350", max_length=10, null=True),
        ),
    ]
