# Generated by Django 4.1.7 on 2023-09-19 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevis", "0007_sevisinformationuser_sevis_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="sevisinformationuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 9, 19, 18, 39, 48, 67676),
            ),
            preserve_default=False,
        ),
    ]
