# Generated by Django 4.1.7 on 2023-09-21 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevis", "0008_sevisinformationuser_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sevisinformationguest",
            name="charges",
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name="sevisinformationguest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 9, 21, 17, 15, 44, 955166),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sevisinformationguest",
            name="order_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="sevisinformationguest",
            name="sevis_fee",
            field=models.IntegerField(default=350),
        ),
        migrations.AlterField(
            model_name="sevisinformationguest",
            name="fee_in_dollars",
            field=models.IntegerField(default=385),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sevisinformationguest",
            name="fee_in_naira",
            field=models.IntegerField(default=269500),
            preserve_default=False,
        ),
    ]
