# Generated by Django 4.1.7 on 2023-09-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevis", "0010_alter_sevisinformationguest_fee_in_dollars_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sevisinformationguest",
            name="payment_status",
            field=models.CharField(
                blank=True, default="Payment Pending", max_length=100, null=True
            ),
        ),
    ]
