# Generated by Django 4.1.7 on 2023-09-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevis", "0011_sevisinformationguest_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sevisinformationguest",
            name="rate",
            field=models.IntegerField(default=700),
        ),
    ]
