# Generated by Django 4.1.7 on 2023-09-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevis", "0013_remove_sevisinformationguest_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sevisinformationguest",
            name="sevis_coupon",
            field=models.FileField(blank=True, null=True, upload_to="sevis_coupon/"),
        ),
    ]
