# Generated by Django 4.1.7 on 2023-09-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevis", "0014_sevisinformationguest_sevis_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="sevisinformationguest",
            name="passport",
            field=models.ImageField(blank=True, null=True, upload_to="passport/"),
        ),
    ]
