# Generated by Django 4.1.7 on 2023-09-24 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sevis", "0016_alter_sevisinformationuser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sevisinformationuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_sevis_information",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
