# Generated by Django 4.1.7 on 2023-10-08 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sevis", "0018_sevisinformationuser_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sevisinformationguest",
            name="passport",
        ),
        migrations.AlterField(
            model_name="sevisinformationguest",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="sevisinformationuser",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
