# Generated by Django 4.1.7 on 2023-10-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevis", "0019_remove_sevisinformationguest_passport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sevisinformationguest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sevisinformationuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
