# Generated by Django 4.1.7 on 2023-08-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.CharField(
                choices=[
                    ("payment", "Payment"),
                    ("account", "Account"),
                    ("security", "Security"),
                ],
                default="payment",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
