# Generated by Django 4.1.7 on 2023-07-18 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_picture/"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=25)),
                ("country_of_residence", models.CharField(max_length=45)),
                (
                    "institution_of_study",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country_code", models.IntegerField(default=234)),
                ("phone_number", models.CharField(max_length=10, unique=True)),
                (
                    "address_book",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "transaction_pin",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "confirm_transaction_pin",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "security_question_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "security_answer_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "security_question_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "security_answer_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "security_question_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "security_answer_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("wallet_id", models.CharField(max_length=10, null=True, unique=True)),
                ("otp", models.CharField(blank=True, max_length=4, null=True)),
                ("otp_expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SecurityQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("security_question", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="SevisInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sevis_id", models.CharField(max_length=100)),
                ("given_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("form", models.FileField(upload_to="form/")),
                ("passport", models.ImageField(upload_to="passport/")),
                ("form_type", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("I_20_email", models.CharField(max_length=100)),
                ("I_20_country_of_citizenship", models.CharField(max_length=100)),
                ("I_20_country_of_birth", models.CharField(max_length=100)),
                ("I_20_country", models.CharField(max_length=200)),
                ("street_address_1", models.CharField(max_length=200)),
                ("street_address_2", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                (
                    "fee_in_dollars",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "fee_in_naira",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sevis_information",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_fee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
