# Generated by Django 4.1.7 on 2023-07-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_sevisinformation_international_passport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sevisinformation",
            name="I_20_phone_number",
            field=models.CharField(default="+2348126087499", max_length=15),
        ),
    ]
