# Generated by Django 4.1.7 on 2023-07-20 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_sevisinformation_i_20_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="address_book",
        ),
        migrations.CreateModel(
            name="AddressBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_address", models.CharField(max_length=200)),
                (
                    "apartment_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("city", models.CharField(max_length=256)),
                ("country", models.CharField(max_length=256)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_book",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
