# Generated by Django 4.1.7 on 2023-07-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_customuser_address_book_addressbook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sevisinformation",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
