# Generated by Django 4.1.7 on 2023-07-26 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_faqs_alter_sevisinformation_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFAQs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", models.CharField(max_length=10000)),
                (
                    "faq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.faqs"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_faq",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
