# Generated by Django 4.1.7 on 2023-07-28 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_consultation_delete_userfaq"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SecurityQuestions",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="confirm_transaction_pin",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="security_answer_1",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="security_answer_2",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="security_answer_3",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="security_question_1",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="security_question_2",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="security_question_3",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="transaction_pin",
        ),
        migrations.AlterField(
            model_name="consultation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_consultation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
