# Generated by Django 4.1.7 on 2023-07-28 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_delete_securityquestions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="consultation_way",
            field=models.CharField(default="Phone", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultation",
            name="date",
            field=models.DateField(default="2023-10-22"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultation",
            name="phone_number",
            field=models.CharField(default=2345678987, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultation",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultation",
            name="time_of_consultation",
            field=models.CharField(default="Later", max_length=10),
            preserve_default=False,
        ),
    ]
