# Generated by Django 4.1.7 on 2023-07-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_consultation_consultation_way_consultation_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
