# Generated by Django 4.1.7 on 2023-07-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_consultation_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="consultation_way",
            field=models.CharField(max_length=20),
        ),
    ]
