# Generated by Django 4.1.7 on 2023-07-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_consultation_consultation_way"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
