# Generated by Django 4.1.7 on 2023-07-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_consultation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="time",
            field=models.TimeField(null=True),
        ),
    ]
