# Generated by Django 4.1.7 on 2023-07-31 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_consultation_date_alter_consultation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sevisinformation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sevis_information",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
