# Generated by Django 4.1.7 on 2023-08-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_alter_addressbook_user_alter_consultation_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(),
        ),
    ]
