# Generated by Django 4.1.7 on 2023-08-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_alter_faq_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="fee_in_dollars",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="fee_in_naira",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="consultation_way",
            field=models.CharField(
                choices=[("zoom", "Zoom Video Call"), ("phone", "Phone Call")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="time_of_consultation",
            field=models.CharField(
                choices=[("today", "Today"), ("later", "Later")], max_length=10
            ),
        ),
    ]
