# Generated by Django 4.1.7 on 2023-08-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_alter_consultation_consultation_way"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SevisInformation",
        ),
    ]
