# Generated by Django 4.1.7 on 2023-08-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_sevisinformation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SevisInformation",
        ),
    ]
