# Generated by Django 4.1.7 on 2023-08-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_delete_sevisinformation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Faq",
        ),
    ]
