# Generated by Django 4.1.7 on 2023-08-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_delete_faq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultation",
            name="user",
        ),
        migrations.DeleteModel(
            name="ApplicationFee",
        ),
        migrations.DeleteModel(
            name="Consultation",
        ),
    ]
