# Generated by Django 4.1.7 on 2023-08-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_orderhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country_of_residence",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
