# Generated by Django 4.1.7 on 2023-08-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_remove_addressbook_apartment_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderhistory",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=200500, max_digits=20),
            preserve_default=False,
        ),
    ]
