# Generated by Django 4.1.7 on 2023-08-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_orderhistory_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderhistory",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
