# Generated by Django 4.1.7 on 2023-08-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_alter_orderhistory_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
    ]
