# Generated by Django 4.1.7 on 2023-08-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0040_customuser_profile_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_restricted",
            field=models.BooleanField(default=False),
        ),
    ]
