# Generated by Django 4.1.7 on 2023-08-29 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_customuser_city_customuser_country_of_birth_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AddressBook",
        ),
    ]
