# Generated by Django 4.1.7 on 2023-09-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_delete_addressbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("consultant", "Consultant"),
                    ("instaitution", "Institution"),
                ],
                default="user",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
