# Generated by Django 4.1.7 on 2023-09-03 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_alter_customuser_user_type_consultant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
