# Generated by Django 4.1.7 on 2023-09-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0047_alter_consultant_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultant",
            name="location",
        ),
        migrations.AddField(
            model_name="consultant",
            name="bio",
            field=models.TextField(default="vefhvuiherveur"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultant",
            name="country",
            field=models.CharField(default="Nigeria", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultant",
            name="qualification",
            field=models.CharField(default="Civil Engineering", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultant",
            name="state",
            field=models.CharField(default="Lagos", max_length=256),
            preserve_default=False,
        ),
    ]
