# Generated by Django 4.1.7 on 2023-09-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_remove_consultant_location_consultant_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country_of_residence",
            field=models.CharField(default="Nigeria", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=256),
        ),
    ]
