# Generated by Django 4.1.7 on 2023-09-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_alter_customuser_country_of_residence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="free_consultation",
            field=models.BooleanField(default=True),
        ),
    ]
