# Generated by Django 4.1.7 on 2023-09-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_customuser_otp_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_picture/"
            ),
        ),
    ]
