# Generated by Django 4.1.7 on 2023-09-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_consultant_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="price_per_hour",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="years_of_experience",
            field=models.IntegerField(),
        ),
    ]
