# Generated by Django 4.1.7 on 2023-09-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0054_orderhistoryguest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderhistory",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
