# Generated by Django 4.1.7 on 2023-09-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_alter_orderhistory_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderhistoryguest",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
