# Generated by Django 4.1.7 on 2023-08-04 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consultation", models.CharField(max_length=10000)),
                ("details", models.CharField(max_length=10000)),
                (
                    "consultation_way",
                    models.CharField(
                        choices=[
                            ("zoom video call", "Zoom Video Call"),
                            ("phone call", "Phone Call"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "time_of_consultation",
                    models.CharField(
                        choices=[("today", "Today"), ("later", "Later")], max_length=10
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("time", models.TimeField(null=True)),
                ("fee_in_naira", models.IntegerField(blank=True, null=True)),
                ("fee_in_dollars", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_consultation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
