# Generated by Django 4.1.7 on 2023-09-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultation", "0004_alter_consultation_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultation",
            name="consultation_way",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="date",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="time",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="time_of_consultation",
        ),
    ]
