# Generated by Django 4.1.7 on 2023-09-03 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("consultation", "0005_remove_consultation_consultation_way_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_consultation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
