# Generated by Django 4.1.7 on 2023-09-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultation", "0006_alter_consultation_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consultation", models.CharField(max_length=10000)),
                ("details", models.CharField(max_length=10000)),
                ("fee_in_naira", models.IntegerField(blank=True, null=True)),
                ("fee_in_dollars", models.IntegerField(blank=True, null=True)),
                ("order_id", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
