# Generated by Django 4.1.7 on 2023-09-05 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_remove_consultant_location_consultant_bio_and_more"),
        ("consultation", "0007_consultationguest"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="consultant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultant",
                to="accounts.consultant",
            ),
            preserve_default=False,
        ),
    ]
