# Generated by Django 4.1.7 on 2023-09-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultation", "0010_consultation_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="consultation_fee",
            field=models.IntegerField(blank=True, default=350, null=True),
        ),
    ]
