# Generated by Django 4.1.7 on 2023-09-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultation", "0011_consultation_consultation_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultation",
            name="consultation_fee",
        ),
    ]
