# Generated by Django 4.1.7 on 2023-09-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultation", "0013_consultation_consultation_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="consultation_fee",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
